language: objective-c
before_install:
    - gem install ios_ci
    - brew install ios-sim

script: ios_ci cedar --source-root $TRAVIS_BUILD_DIR/Example --workspace CRDI.xcworkspace --scheme CRDISpecs --build-path Build/Products
